/// English texts of the shared enums and catalogs (key → text).
const sharedEn = <String, String>{
  "MemberRole.adult": "Adult",
  "MemberRole.child": "Child",
  "MemberRole.guest": "Guest",
  "MemberRole.service": "Service account",
  "ServiceAccess.full": "Read and change",
  "ServiceAccess.everyday": "Tick off and shopping",
  "ServiceAccess.readOnly": "Read only",
  "TwoFactorPolicy.admins": "Administrators",
  "TwoFactorPolicy.all": "All members",
  "GermanState.bw": "Baden-Württemberg",
  "GermanState.by": "Bavaria",
  "GermanState.be": "Berlin",
  "GermanState.bb": "Brandenburg",
  "GermanState.hb": "Bremen",
  "GermanState.hh": "Hamburg",
  "GermanState.he": "Hesse",
  "GermanState.mv": "Mecklenburg-Western Pomerania",
  "GermanState.ni": "Lower Saxony",
  "GermanState.nw": "North Rhine-Westphalia",
  "GermanState.rp": "Rhineland-Palatinate",
  "GermanState.sl": "Saarland",
  "GermanState.sn": "Saxony",
  "GermanState.st": "Saxony-Anhalt",
  "GermanState.sh": "Schleswig-Holstein",
  "GermanState.th": "Thuringia",
  "MilestoneArea.motor": "Movement",
  "MilestoneArea.fineMotor": "Hands & dexterity",
  "MilestoneArea.language": "Language",
  "MilestoneArea.social": "Feelings & social",
  "MilestoneArea.selfCare": "Independence",
  "MilestoneArea.body": "Body",
  "ChoreRepeat.once": "Once",
  "ChoreRepeat.daily": "Daily",
  "ChoreRepeat.weekly": "Once a week",
  "MoneyKind.allowance": "Pocket money",
  "MoneyKind.points": "Points exchanged",
  "MoneyKind.spent": "Spent",
  "MoneyKind.gift": "Gift",
  "MoneyKind.other": "Other",
  "ContactRole.pediatrician": "Pediatrician",
  "ContactRole.doctor": "Doctor",
  "ContactRole.dentist": "Dentist",
  "ContactRole.midwife": "Midwife",
  "ContactRole.clinic": "Hospital",
  "ContactRole.daycare": "Daycare",
  "ContactRole.school": "School",
  "ContactRole.babysitter": "Babysitter",
  "ContactRole.family": "Family & friends",
  "ContactRole.emergency": "Emergency service",
  "ContactRole.other": "Other",
  "DocumentCategory.identity": "IDs & passports",
  "DocumentCategory.health": "Health",
  "DocumentCategory.school": "School & daycare",
  "DocumentCategory.insurance": "Insurance",
  "DocumentCategory.finance": "Finances & taxes",
  "DocumentCategory.home": "House & home",
  "DocumentCategory.contracts": "Contracts",
  "DocumentCategory.photos": "Photos",
  "DocumentCategory.other": "Other",
  "PantryPlace.fridge": "Fridge",
  "PantryPlace.freezer": "Freezer",
  "PantryPlace.pantry": "Pantry",
  "PantryPlace.other": "Other",
  "LogKind.breast": "Breastfeeding",
  "LogKind.bottle": "Bottle",
  "LogKind.solids": "Solids",
  "LogKind.pumping": "Pumping",
  "LogKind.sleep": "Sleep",
  "LogKind.diaper": "Diaper",
  "LogKind.temperature": "Temperature",
  "LogKind.medication": "Medication",
  "LogKind.symptom": "Symptom",
  "LogKind.bath": "Bath",
  "BreastSide.left": "left",
  "BreastSide.right": "right",
  "MilkKind.breastMilk": "Breast milk",
  "MilkKind.formula": "Formula",
  "MilkKind.other": "Other",
  "DiaperKind.wet": "wet",
  "DiaperKind.dirty": "dirty",
  "DiaperKind.both": "wet + dirty",
  "WasteKind.residual": "Residual waste",
  "WasteKind.organic": "Organic waste",
  "WasteKind.paper": "Paper",
  "WasteKind.packaging": "Packaging",
  "WasteKind.glass": "Glass",
  "WasteKind.garden": "Garden waste",
  "WasteKind.bulky": "Bulky waste",
  "WasteKind.hazardous": "Hazardous waste",
  "WasteKind.other": "Collection",
  "MealSlot.breakfast": "Breakfast",
  "MealSlot.lunch": "Lunch",
  "MealSlot.dinner": "Dinner",
  "MealSlot.snack": "Snack",
  "DeadlineArea.car": "Car",
  "DeadlineArea.home": "House & home",
  "DeadlineArea.pet": "Pets",
  "DeadlineArea.other": "Other",
  "Checklist|Kliniktasche": "Hospital bag",
  "Checklist|Erstausstattung": "Baby essentials",
  "Checklist|Nach der Geburt": "After the birth",
  "Holiday|Neujahr": "New Year's Day",
  "Holiday|Heilige Drei Könige": "Epiphany",
  "Holiday|Karfreitag": "Good Friday",
  "Holiday|Ostermontag": "Easter Monday",
  "Holiday|Tag der Arbeit": "Labor Day",
  "Holiday|Christi Himmelfahrt": "Ascension Day",
  "Holiday|Pfingstmontag": "Whit Monday",
  "Holiday|Fronleichnam": "Corpus Christi",
  "Holiday|Tag der Deutschen Einheit": "German Unity Day",
  "Holiday|Allerheiligen": "All Saints' Day",
  "Holiday|1. Weihnachtstag": "Christmas Day",
  "Holiday|2. Weihnachtstag": "Boxing Day",
  "Holiday|Internationaler Frauentag": "International Women's Day",
  "Holiday|Ostersonntag": "Easter Sunday",
  "Holiday|Pfingstsonntag": "Whit Sunday",
  "Holiday|Reformationstag": "Reformation Day",
  "Holiday|Mariä Himmelfahrt": "Assumption Day",
  "Holiday|Buß- und Bettag": "Day of Repentance and Prayer",
  "Holiday|Weltkindertag": "World Children's Day",
  "ShoppingCategory.produce": "Fruit & vegetables",
  "ShoppingCategory.bakery": "Bread & bakery",
  "ShoppingCategory.dairy": "Chilled",
  "ShoppingCategory.meat": "Meat, cold cuts & fish",
  "ShoppingCategory.frozen": "Frozen",
  "ShoppingCategory.pantry": "Pasta, rice & cans",
  "ShoppingCategory.baking": "Baking & spices",
  "ShoppingCategory.drinks": "Drinks",
  "ShoppingCategory.snacks": "Sweets & snacks",
  "ShoppingCategory.household": "Drugstore & household",
  "ShoppingCategory.baby": "Baby & child",
  "ShoppingCategory.pet": "Pet supplies",
  "ShoppingCategory.other": "Other",
  "DeadlinePreset|HU/TÜV": "Car inspection",
  "DeadlinePreset|Monat steht auf der Plakette am hinteren Kennzeichen":
      "The month is on the sticker on the rear license plate",
  "DeadlinePreset|Inspektion": "Service",
  "DeadlinePreset|Winterreifen aufziehen": "Put on winter tires",
  "DeadlinePreset|Faustregel: von Oktober bis Ostern":
      "Rule of thumb: from October to Easter",
  "DeadlinePreset|Sommerreifen aufziehen": "Put on summer tires",
  "DeadlinePreset|Kfz-Versicherung prüfen": "Check car insurance",
  "DeadlinePreset|Verbandkasten tauschen": "Replace the first aid kit",
  "DeadlinePreset|Heizungswartung": "Heating maintenance",
  "DeadlinePreset|Rauchmelder testen": "Test smoke detectors",
  "DeadlinePreset|Schornsteinfeger": "Chimney sweep",
  "DeadlinePreset|Wasserfilter wechseln": "Change water filter",
  "DeadlinePreset|Feuerlöscher prüfen": "Check fire extinguisher",
  "DeadlinePreset|Zählerstände ablesen": "Read the meters",
  "DeadlinePreset|Impfung": "Vaccination",
  "DeadlinePreset|Entwurmung": "Deworming",
  "DeadlinePreset|Floh- und Zeckenschutz": "Flea and tick protection",
  "DeadlinePreset|Tierarzt-Check": "Vet checkup",
  "DeadlinePreset|Hundesteuer": "Dog tax",
  "ListTemplate|Urlaub": "Vacation",
  "ListTemplate|Kita-Tasche": "Daycare bag",
  "ListTemplate|Kliniktasche Geburt": "Hospital bag for the birth",
  "ListTemplate|Schwimmbad": "Swimming pool",
  "ListTemplate|Camping": "Camping",
  "CheckIn|Bin angekommen": "I've arrived",
  "CheckIn|Alles ok": "All okay",
  "CheckIn|Bin auf dem Heimweg": "On my way home",
  "CheckIn|Bitte abholen": "Please pick me up",
  "LocationAlert|{member} ist bei „{place}“ angekommen":
      "{member} arrived at “{place}”",
  "LocationAlert|{member} hat „{place}“ verlassen": "{member} left “{place}”",
  "LocationAlert|{member}: {note} (bei „{place}“)":
      "{member}: {note} (at “{place}”)",
  "Recurrence|täglich": "daily",
  "Recurrence|alle {every} Tage": "every {every} days",
  "Recurrence|wöchentlich": "weekly",
  "Recurrence|alle {every} Wochen": "every {every} weeks",
  "Recurrence|monatlich": "monthly",
  "Recurrence|alle {every} Monate": "every {every} months",
  "Recurrence|jährlich": "yearly",
  "Recurrence|alle {every} Jahre": "every {every} years",
  "Milestone|Hebt in Bauchlage kurz den Kopf":
      "Briefly lifts the head when lying on the tummy",
  "Milestone|Hält den Kopf sicher": "Holds the head steady",
  "Milestone|Dreht sich vom Rücken auf den Bauch": "Rolls from back to tummy",
  "Milestone|Sitzt frei ohne Stütze": "Sits without support",
  "Milestone|Krabbelt auf Händen und Knien": "Crawls on hands and knees",
  "Milestone|Manche Kinder lassen das Krabbeln ganz aus – das ist normal.":
      "Some children skip crawling entirely – that's normal.",
  "Milestone|Steht mit Festhalten": "Stands while holding on",
  "Milestone|Läuft an Möbeln entlang": "Cruises along furniture",
  "Milestone|Steht frei": "Stands alone",
  "Milestone|Erste freie Schritte": "First steps alone",
  "Milestone|Geht Treppen mit Festhalten": "Climbs stairs holding on",
  "Milestone|Rennt": "Runs",
  "Milestone|Springt mit beiden Beinen": "Jumps with both feet",
  "Milestone|Fährt Laufrad oder Dreirad": "Rides a balance bike or tricycle",
  "Milestone|Steht kurz auf einem Bein": "Stands briefly on one leg",
  "Milestone|Fährt Fahrrad ohne Stützräder":
      "Rides a bike without training wheels",
  "Milestone|Schwimmt (Seepferdchen)": "Swims (first swimming badge)",
  "Milestone|Greift gezielt nach Dingen": "Reaches for things on purpose",
  "Milestone|Gibt Dinge von einer Hand in die andere":
      "Passes things from one hand to the other",
  "Milestone|Pinzettengriff mit Daumen und Zeigefinger":
      "Pincer grasp with thumb and index finger",
  "Milestone|Baut einen Turm aus Klötzen": "Builds a tower of blocks",
  "Milestone|Kritzelt mit Stift": "Scribbles with a pen",
  "Milestone|Malt einen Kreis": "Draws a circle",
  "Milestone|Schneidet mit der Kinderschere": "Cuts with child scissors",
  "Milestone|Malt einen Menschen mit Kopf, Armen und Beinen":
      "Draws a person with head, arms and legs",
  "Milestone|Gurrt und macht Vokal-Laute": "Coos and makes vowel sounds",
  "Milestone|Brabbelt Silbenketten („ba-ba-ba“)":
      "Babbles syllable chains (“ba-ba-ba”)",
  "Milestone|Erstes Wort mit Bedeutung": "First word with meaning",
  "Milestone|Zweiwortsätze („Mama Auto“)": "Two-word sentences (“Mommy car”)",
  "Milestone|Spricht in kurzen Sätzen": "Speaks in short sentences",
  "Milestone|Stellt „Warum?“-Fragen": "Asks “why?” questions",
  "Milestone|Erzählt kleine Geschichten": "Tells little stories",
  "Milestone|Liest erste Wörter": "Reads first words",
  "Milestone|Erstes soziales Lächeln": "First social smile",
  "Milestone|Lacht laut": "Laughs out loud",
  "Milestone|Fremdelt": "Stranger anxiety",
  "Milestone|Winkt „Tschüss“": "Waves “bye-bye”",
  "Milestone|Als-ob-Spiel (füttert die Puppe)": "Pretend play (feeds the doll)",
  "Milestone|Spielt gemeinsam mit anderen Kindern":
      "Plays together with other children",
  "Milestone|Hat eine beste Freundin / einen besten Freund":
      "Has a best friend",
  "Milestone|Trinkt aus dem Becher": "Drinks from a cup",
  "Milestone|Isst selbst mit dem Löffel": "Eats with a spoon by themselves",
  "Milestone|Tagsüber trocken": "Dry during the day",
  "Milestone|Nachts trocken": "Dry at night",
  "Milestone|Nachts trocken zu werden dauert oft deutlich länger als tagsüber.":
      "Becoming dry at night often takes much longer than during the day.",
  "Milestone|Zieht sich allein an": "Gets dressed alone",
  "Milestone|Bindet Schuhe selbst": "Ties shoes by themselves",
  "Milestone|Erster Zahn": "First tooth",
  "Milestone|Schläft (meist) durch": "Sleeps through the night (mostly)",
  "Milestone|Erster Wackelzahn": "First loose tooth",
  "Checkup|U1 – Neugeborenen-Erstuntersuchung":
      "U1 – first newborn examination",
  "Checkup|direkt nach der Geburt": "right after the birth",
  "Checkup|U2 – Neugeborenen-Basisuntersuchung":
      "U2 – basic newborn examination",
  "Checkup|3.–10. Lebenstag": "day 3–10 of life",
  "Checkup|U3": "U3",
  "Checkup|4.–5. Lebenswoche": "week 4–5 of life",
  "Checkup|U4": "U4",
  "Checkup|3.–4. Lebensmonat": "month 3–4 of life",
  "Checkup|U5": "U5",
  "Checkup|6.–7. Lebensmonat": "month 6–7 of life",
  "Checkup|U6": "U6",
  "Checkup|10.–12. Lebensmonat": "month 10–12 of life",
  "Checkup|U7": "U7",
  "Checkup|21.–24. Lebensmonat": "month 21–24 of life",
  "Checkup|U7a": "U7a",
  "Checkup|34.–36. Lebensmonat": "month 34–36 of life",
  "Checkup|U8": "U8",
  "Checkup|46.–48. Lebensmonat": "month 46–48 of life",
  "Checkup|U9 – vor der Einschulung": "U9 – before starting school",
  "Checkup|60.–64. Lebensmonat": "month 60–64 of life",
  "Checkup|U10": "U10",
  "Checkup|7–8 Jahre": "7–8 years",
  "Checkup|U11": "U11",
  "Checkup|9–10 Jahre": "9–10 years",
  "Checkup|J1 – Jugenduntersuchung": "J1 – adolescent checkup",
  "Checkup|12–14 Jahre": "12–14 years",
  "Checkup|J2": "J2",
  "Checkup|16–17 Jahre": "16–17 years",
  "Vaccination|RSV (Antikörper-Prophylaxe)": "RSV (antibody prophylaxis)",
  "Vaccination|einmalig": "once",
  "Vaccination|Vor bzw. in der ersten RSV-Saison (meist Oktober–März).":
      "Before or during the first RSV season (usually October–March).",
  "Vaccination|Rotaviren": "Rotavirus",
  "Vaccination|1. Dosis": "1st dose",
  "Vaccination|Schluckimpfung ab 6 Wochen.": "Oral vaccine from 6 weeks.",
  "Vaccination|2. Dosis": "2nd dose",
  "Vaccination|3. Dosis": "3rd dose",
  "Vaccination|Je nach Impfstoff nötig.": "Needed depending on the vaccine.",
  "Vaccination|Sechsfach (Tetanus, Diphtherie, Keuchhusten, Hib, Polio, Hepatitis B)":
      "Six-in-one (tetanus, diphtheria, whooping cough, Hib, polio, hepatitis B)",
  "Vaccination|Pneumokokken": "Pneumococcus",
  "Vaccination|Meningokokken B": "Meningococcus B",
  "Vaccination|Masern, Mumps, Röteln, Windpocken":
      "Measles, mumps, rubella, chickenpox",
  "Vaccination|Meningokokken C": "Meningococcus C",
  "Vaccination|Für Kita und Schule ist der Masernschutz Pflicht.":
      "Measles protection is mandatory for daycare and school (Germany).",
  "Vaccination|Tetanus, Diphtherie, Keuchhusten":
      "Tetanus, diphtheria, whooping cough",
  "Vaccination|Auffrischung": "Booster",
  "Vaccination|Mit 5–6 Jahren.": "At 5–6 years.",
  "Vaccination|HPV (Humane Papillomviren)": "HPV (human papillomavirus)",
  "Vaccination|Mit 9–14 Jahren, für alle Kinder.":
      "At 9–14 years, for all children.",
  "Vaccination|Mindestens 5 Monate nach der 1. Dosis.":
      "At least 5 months after the 1st dose.",
  "Vaccination|Tetanus, Diphtherie, Keuchhusten, Polio":
      "Tetanus, diphtheria, whooping cough, polio",
  "Vaccination|Mit 9–16 Jahren.": "At 9–16 years.",
  "PregnancyWeek|ein Mohnsamen": "a poppy seed",
  "PregnancyWeek|Die Einnistung ist geschafft.": "Implantation is done.",
  "PregnancyWeek|ein Sesamkorn": "a sesame seed",
  "PregnancyWeek|Das Herz beginnt sich zu bilden.": "The heart begins to form.",
  "PregnancyWeek|eine Linse": "a lentil",
  "PregnancyWeek|Im Ultraschall ist oft schon der Herzschlag zu sehen.":
      "The heartbeat can often already be seen on the ultrasound.",
  "PregnancyWeek|eine Blaubeere": "a blueberry",
  "PregnancyWeek|Ärmchen und Beinchen knospen.":
      "Little arms and legs are budding.",
  "PregnancyWeek|eine Himbeere": "a raspberry",
  "PregnancyWeek|Finger und Zehen entstehen.": "Fingers and toes are forming.",
  "PregnancyWeek|eine Kirsche": "a cherry",
  "PregnancyWeek|Alle Organe sind angelegt.": "All organs are in place.",
  "PregnancyWeek|eine Erdbeere": "a strawberry",
  "PregnancyWeek|Aus dem Embryo wird ein Fötus.": "The embryo becomes a fetus.",
  "PregnancyWeek|eine Feige": "a fig",
  "PregnancyWeek|Das Baby bewegt sich schon – spüren kann man es noch nicht.":
      "The baby is already moving – it can't be felt yet.",
  "PregnancyWeek|eine Limette": "a lime",
  "PregnancyWeek|Das erste Drittel ist bald geschafft.":
      "The first trimester is almost done.",
  "PregnancyWeek|eine Zitrone": "a lemon",
  "PregnancyWeek|Das zweite Trimester beginnt.": "The second trimester begins.",
  "PregnancyWeek|ein Pfirsich": "a peach",
  "PregnancyWeek|Das Baby kann schon Grimassen schneiden.":
      "The baby can already make faces.",
  "PregnancyWeek|ein Apfel": "an apple",
  "PregnancyWeek|Die Haut ist noch ganz dünn.": "The skin is still very thin.",
  "PregnancyWeek|eine Avocado": "an avocado",
  "PregnancyWeek|Manche spüren jetzt erste Bewegungen.":
      "Some feel the first movements now.",
  "PregnancyWeek|eine Birne": "a pear",
  "PregnancyWeek|Fettpolster beginnen sich zu bilden.":
      "Fat pads begin to form.",
  "PregnancyWeek|eine Paprika": "a bell pepper",
  "PregnancyWeek|Das Baby hört erste Geräusche.":
      "The baby hears its first sounds.",
  "PregnancyWeek|eine Mango": "a mango",
  "PregnancyWeek|Bergfest naht!": "Halfway there soon!",
  "PregnancyWeek|eine Banane": "a banana",
  "PregnancyWeek|Halbzeit – ab jetzt wird von Kopf bis Fuß gemessen.":
      "Halfway – from now on it is measured from head to toe.",
  "PregnancyWeek|eine Karotte": "a carrot",
  "PregnancyWeek|Tritte werden kräftiger.": "Kicks get stronger.",
  "PregnancyWeek|eine Papaya": "a papaya",
  "PregnancyWeek|Das Baby erkennt Stimmen.": "The baby recognizes voices.",
  "PregnancyWeek|eine Grapefruit": "a grapefruit",
  "PregnancyWeek|Die Lunge reift.": "The lungs are maturing.",
  "PregnancyWeek|ein Maiskolben": "an ear of corn",
  "PregnancyWeek|Ab jetzt hat ein Frühchen gute Chancen.":
      "From now on a preemie has a good chance.",
  "PregnancyWeek|ein Blumenkohl": "a cauliflower",
  "PregnancyWeek|Das Baby hat einen Schlaf-Wach-Rhythmus.":
      "The baby has a sleep-wake rhythm.",
  "PregnancyWeek|ein Salatkopf": "a head of lettuce",
  "PregnancyWeek|Die Augen öffnen sich.": "The eyes open.",
  "PregnancyWeek|ein Brokkoli": "a broccoli",
  "PregnancyWeek|Das zweite Trimester endet.": "The second trimester ends.",
  "PregnancyWeek|eine Aubergine": "an eggplant",
  "PregnancyWeek|Das letzte Drittel beginnt.": "The last trimester begins.",
  "PregnancyWeek|ein Butternusskürbis": "a butternut squash",
  "PregnancyWeek|Muskeln und Lunge reifen weiter.":
      "Muscles and lungs keep maturing.",
  "PregnancyWeek|ein Kohlkopf": "a cabbage",
  "PregnancyWeek|Das Gehirn wächst schnell.": "The brain is growing fast.",
  "PregnancyWeek|eine Kokosnuss": "a coconut",
  "PregnancyWeek|Es wird eng im Bauch.": "It is getting tight in the belly.",
  "PregnancyWeek|ein Hokkaido-Kürbis": "a red kuri squash",
  "PregnancyWeek|Die meisten Babys drehen sich jetzt mit dem Kopf nach unten.":
      "Most babies turn head down now.",
  "PregnancyWeek|eine Ananas": "a pineapple",
  "PregnancyWeek|Die Knochen härten aus – bis auf den Schädel.":
      "The bones harden – except for the skull.",
  "PregnancyWeek|eine Honigmelone": "a honeydew melon",
  "PregnancyWeek|Zeit, die Kliniktasche zu packen.":
      "Time to pack the hospital bag.",
  "PregnancyWeek|eine Galiamelone": "a galia melon",
  "PregnancyWeek|Das Baby legt vor allem an Gewicht zu.":
      "The baby mainly gains weight.",
  "PregnancyWeek|ein Römersalat": "a romaine lettuce",
  "PregnancyWeek|Ab jetzt heißt es: bereit sein.": "From now on: be ready.",
  "PregnancyWeek|ein Mangold": "a bunch of chard",
  "PregnancyWeek|Ab 37+0 gilt das Baby als reif geboren.":
      "From 37+0 the baby counts as full-term.",
  "PregnancyWeek|eine Lauchstange": "a leek",
  "PregnancyWeek|Jeden Tag kann es losgehen.": "It can start any day.",
  "PregnancyWeek|eine kleine Wassermelone": "a small watermelon",
  "PregnancyWeek|Die Käseschmiere wird weniger.": "The vernix is getting less.",
  "PregnancyWeek|ein Kürbis": "a pumpkin",
  "PregnancyWeek|Der errechnete Termin ist da – nur wenige Babys kommen genau heute.":
      "The due date is here – only a few babies come exactly today.",
  "PregnancyTask|Hebamme suchen": "Find a midwife",
  "PregnancyTask|Hebammen sind oft früh ausgebucht – für Vorsorge und Wochenbett am besten gleich nach dem positiven Test anfragen.":
      "Midwives are often booked up early – best ask right after the positive test, for prenatal care and the time after the birth.",
  "PregnancyTask|1. Ultraschall-Screening": "1st ultrasound screening",
  "PregnancyTask|Mutterpass: 9+0 bis 12+6.": "Maternity record: 9+0 to 12+6.",
  "PregnancyTask|Geburtsvorbereitungskurs anmelden":
      "Sign up for a birth preparation class",
  "PregnancyTask|Der Kurs selbst liegt meist zwischen SSW 25 und 35.":
      "The class itself is usually between week 25 and 35.",
  "PregnancyTask|2. Ultraschall-Screening": "2nd ultrasound screening",
  "PregnancyTask|Mutterpass: 19+0 bis 22+6.": "Maternity record: 19+0 to 22+6.",
  "PregnancyTask|Zuckertest (Glukose)": "Glucose test",
  "PregnancyTask|Test auf Schwangerschaftsdiabetes: 24+0 bis 27+6.":
      "Test for gestational diabetes: 24+0 to 27+6.",
  "PregnancyTask|Keuchhusten-Impfung": "Whooping cough vaccination",
  "PregnancyTask|STIKO: zu Beginn des letzten Drittels – schützt das Baby in den ersten Monaten.":
      "STIKO: at the start of the last trimester – protects the baby in the first months.",
  "PregnancyTask|3. Ultraschall-Screening": "3rd ultrasound screening",
  "PregnancyTask|Mutterpass: 29+0 bis 32+6.": "Maternity record: 29+0 to 32+6.",
  "PregnancyTask|In der Geburtsklinik anmelden":
      "Register at the maternity clinic",
  "PregnancyTask|Oft mit Vorgespräch und Kreißsaalführung.":
      "Often with a preliminary talk and a delivery room tour.",
  "PregnancyTask|Kinderarzt suchen": "Find a pediatrician",
  "PregnancyTask|Für die U2 und die weiteren Vorsorgen.":
      "For the U2 and the following checkups.",
  "PregnancyTask|Kliniktasche packen": "Pack the hospital bag",
  "PregnancyTask|Siehe Checkliste.": "See the checklist.",
  "PregnancyTask|Mutterschaftsgeld beantragen": "Apply for maternity benefit",
  "PregnancyTask|Bei der Krankenkasse, mit Bescheinigung über den Termin (frühestens 7 Wochen vor ET). Mutterschutz beginnt 6 Wochen vor ET.":
      "At the health insurance, with a certificate of the due date (at the earliest 7 weeks before it). Maternity leave starts 6 weeks before the due date (Germany).",
  "ChecklistItem|Mutterpass, Versichertenkarte, Personalausweis":
      "Maternity record, insurance card, ID card",
  "ChecklistItem|Familienstammbuch bzw. Geburts-/Heiratsurkunde":
      "Family register or birth/marriage certificate",
  "ChecklistItem|Bequeme Kleidung, Bademantel, Hausschuhe":
      "Comfortable clothes, bathrobe, slippers",
  "ChecklistItem|Still-BH, Stilleinlagen, Wochenbett-Unterhosen":
      "Nursing bra, nursing pads, postpartum underwear",
  "ChecklistItem|Kulturbeutel, Haargummi, Lippenpflege":
      "Toiletry bag, hair tie, lip balm",
  "ChecklistItem|Snacks und Getränke für die Geburt":
      "Snacks and drinks for the birth",
  "ChecklistItem|Handy-Ladekabel": "Phone charger",
  "ChecklistItem|Babykleidung für die Heimfahrt (Body, Strampler, Mütze, Jäckchen)":
      "Baby clothes for the trip home (bodysuit, romper, hat, little jacket)",
  "ChecklistItem|Babyschale fürs Auto (einbauen üben!)":
      "Infant car seat (practice installing it!)",
  "ChecklistItem|Beistellbett oder Babybett mit fester Matratze":
      "Bedside crib or crib with a firm mattress",
  "ChecklistItem|Schlafsäcke (keine Decke, kein Kissen)":
      "Sleeping bags (no blanket, no pillow)",
  "ChecklistItem|Kinderwagen oder Trage": "Stroller or carrier",
  "ChecklistItem|Bodys und Strampler (Gr. 50/56 und 62)":
      "Bodysuits and rompers (sizes 50/56 and 62)",
  "ChecklistItem|Windeln, Feuchttücher oder Waschlappen":
      "Diapers, wet wipes or washcloths",
  "ChecklistItem|Wickelunterlage, Wundschutzcreme":
      "Changing pad, diaper cream",
  "ChecklistItem|Badethermometer, Kapuzenhandtuch":
      "Bath thermometer, hooded towel",
  "ChecklistItem|Fieberthermometer": "Fever thermometer",
  "ChecklistItem|Geburt beim Standesamt anzeigen (innerhalb einer Woche; oft über die Klinik)":
      "Register the birth at the registry office (within a week; often via the clinic)",
  "ChecklistItem|Baby bei der Krankenkasse anmelden":
      "Register the baby with the health insurance",
  "ChecklistItem|Kindergeld bei der Familienkasse beantragen":
      "Apply for child benefit at the family benefits office",
  "ChecklistItem|Elterngeld beantragen (rückwirkend nur 3 Monate)":
      "Apply for parental allowance (only 3 months retroactively)",
  "ChecklistItem|Arbeitgeber informieren, Elternzeit anmelden (7 Wochen vorher)":
      "Inform the employer, register parental leave (7 weeks before)",
  "ChecklistItem|Termin für die U2 (3.–10. Lebenstag)":
      "Appointment for the U2 (day 3–10 of life)",
  "ChecklistItem|Wochenbett-Hebamme bestätigen":
      "Confirm the postpartum midwife",
  "TemplateItem|Ausweise & Reisepässe": "IDs & passports",
  "TemplateItem|Krankenversichertenkarten": "Health insurance cards",
  "TemplateItem|Buchungsbestätigungen": "Booking confirmations",
  "TemplateItem|Unterwäsche & Socken": "Underwear & socks",
  "TemplateItem|Schlafanzüge": "Pajamas",
  "TemplateItem|Regenjacken": "Rain jackets",
  "TemplateItem|Badesachen": "Swimwear",
  "TemplateItem|Zahnbürsten & Zahnpasta": "Toothbrushes & toothpaste",
  "TemplateItem|Sonnencreme": "Sunscreen",
  "TemplateItem|Reiseapotheke": "Travel first aid kit",
  "TemplateItem|Ladegeräte": "Chargers",
  "TemplateItem|Kuscheltier": "Cuddly toy",
  "TemplateItem|Spiele & Bücher für die Fahrt": "Games & books for the trip",
  "TemplateItem|Snacks & Getränke": "Snacks & drinks",
  "TemplateItem|Wechselkleidung": "Change of clothes",
  "TemplateItem|Windeln & Feuchttücher": "Diapers & wet wipes",
  "TemplateItem|Matschhose & Gummistiefel": "Rain pants & rubber boots",
  "TemplateItem|Hausschuhe": "Slippers",
  "TemplateItem|Trinkflasche": "Water bottle",
  "TemplateItem|Brotdose": "Lunch box",
  "TemplateItem|Sonnenhut / Mütze": "Sun hat / cap",
  "TemplateItem|Mutterpass": "Maternity record",
  "TemplateItem|Versichertenkarte & Ausweis": "Insurance card & ID",
  "TemplateItem|Familienstammbuch / Geburtsurkunden":
      "Family register / birth certificates",
  "TemplateItem|Bequeme Kleidung & Bademantel":
      "Comfortable clothes & bathrobe",
  "TemplateItem|Still-BHs & Stilleinlagen": "Nursing bras & nursing pads",
  "TemplateItem|Hausschuhe & warme Socken": "Slippers & warm socks",
  "TemplateItem|Kulturbeutel": "Toiletry bag",
  "TemplateItem|Ladekabel": "Charging cable",
  "TemplateItem|Erstausstattung Baby": "Baby essentials",
  "TemplateItem|Mützchen & Söckchen": "Little hat & socks",
  "TemplateItem|Babyschale fürs Auto": "Infant car seat",
  "TemplateItem|Handtücher": "Towels",
  "TemplateItem|Schwimmflügel": "Water wings",
  "TemplateItem|Duschgel & Shampoo": "Shower gel & shampoo",
  "TemplateItem|Haarbürste": "Hairbrush",
  "TemplateItem|Münzen für den Spind": "Coins for the locker",
  "TemplateItem|Snacks": "Snacks",
  "TemplateItem|Zelt & Heringe": "Tent & pegs",
  "TemplateItem|Schlafsäcke & Isomatten": "Sleeping bags & sleeping mats",
  "TemplateItem|Stirnlampen": "Headlamps",
  "TemplateItem|Campingkocher & Gas": "Camping stove & gas",
  "TemplateItem|Geschirr & Besteck": "Dishes & cutlery",
  "TemplateItem|Mückenschutz": "Insect repellent",
  "TemplateItem|Erste-Hilfe-Set": "First aid kit",
};
