/// Spanish texts of the shared enums and catalogs (key → text).
const sharedEs = <String, String>{
  "MemberRole.adult": "Adulto",
  "MemberRole.child": "Niño",
  "MemberRole.guest": "Invitado",
  "MemberRole.service": "Cuenta de servicio",
  "ServiceAccess.full": "Leer y cambiar",
  "ServiceAccess.everyday": "Marcar y compras",
  "ServiceAccess.readOnly": "Solo lectura",
  "TwoFactorPolicy.admins": "Administradores",
  "TwoFactorPolicy.all": "Todos los miembros",
  "GermanState.bw": "Baden-Wurtemberg",
  "GermanState.by": "Baviera",
  "GermanState.be": "Berlín",
  "GermanState.bb": "Brandeburgo",
  "GermanState.hb": "Bremen",
  "GermanState.hh": "Hamburgo",
  "GermanState.he": "Hesse",
  "GermanState.mv": "Mecklemburgo-Pomerania Occidental",
  "GermanState.ni": "Baja Sajonia",
  "GermanState.nw": "Renania del Norte-Westfalia",
  "GermanState.rp": "Renania-Palatinado",
  "GermanState.sl": "Sarre",
  "GermanState.sn": "Sajonia",
  "GermanState.st": "Sajonia-Anhalt",
  "GermanState.sh": "Schleswig-Holstein",
  "GermanState.th": "Turingia",
  "MilestoneArea.motor": "Movimiento",
  "MilestoneArea.fineMotor": "Manos y habilidad",
  "MilestoneArea.language": "Lenguaje",
  "MilestoneArea.social": "Emociones y relaciones",
  "MilestoneArea.selfCare": "Autonomía",
  "MilestoneArea.body": "Cuerpo",
  "ChoreRepeat.once": "Una vez",
  "ChoreRepeat.daily": "Cada día",
  "ChoreRepeat.weekly": "Una vez por semana",
  "MoneyKind.allowance": "Paga",
  "MoneyKind.points": "Puntos canjeados",
  "MoneyKind.spent": "Gastado",
  "MoneyKind.gift": "Regalo",
  "MoneyKind.other": "Otros",
  "ContactRole.pediatrician": "Pediatra",
  "ContactRole.doctor": "Médico",
  "ContactRole.dentist": "Dentista",
  "ContactRole.midwife": "Matrona",
  "ContactRole.clinic": "Hospital",
  "ContactRole.daycare": "Guardería",
  "ContactRole.school": "Colegio",
  "ContactRole.babysitter": "Canguro",
  "ContactRole.family": "Familia y amigos",
  "ContactRole.emergency": "Urgencias",
  "ContactRole.other": "Otros",
  "DocumentCategory.identity": "Documentos de identidad y pasaportes",
  "DocumentCategory.health": "Salud",
  "DocumentCategory.school": "Colegio y guardería",
  "DocumentCategory.insurance": "Seguros",
  "DocumentCategory.finance": "Finanzas e impuestos",
  "DocumentCategory.home": "Casa y hogar",
  "DocumentCategory.contracts": "Contratos",
  "DocumentCategory.photos": "Fotos",
  "DocumentCategory.other": "Otros",
  "PantryPlace.fridge": "Nevera",
  "PantryPlace.freezer": "Congelador",
  "PantryPlace.pantry": "Despensa",
  "PantryPlace.other": "Otros",
  "LogKind.breast": "Pecho",
  "LogKind.bottle": "Biberón",
  "LogKind.solids": "Sólidos",
  "LogKind.pumping": "Extracción",
  "LogKind.sleep": "Sueño",
  "LogKind.diaper": "Pañal",
  "LogKind.temperature": "Temperatura",
  "LogKind.medication": "Medicamento",
  "LogKind.symptom": "Síntoma",
  "LogKind.bath": "Baño",
  "BreastSide.left": "izquierdo",
  "BreastSide.right": "derecho",
  "MilkKind.breastMilk": "Leche materna",
  "MilkKind.formula": "Leche de fórmula",
  "MilkKind.other": "Otra",
  "DiaperKind.wet": "mojado",
  "DiaperKind.dirty": "sucio",
  "DiaperKind.both": "mojado + sucio",
  "WasteKind.residual": "Resto",
  "WasteKind.organic": "Orgánico",
  "WasteKind.paper": "Papel",
  "WasteKind.packaging": "Envases",
  "WasteKind.glass": "Vidrio",
  "WasteKind.garden": "Poda",
  "WasteKind.bulky": "Voluminosos",
  "WasteKind.hazardous": "Residuos peligrosos",
  "WasteKind.other": "Recogida",
  "MealSlot.breakfast": "Desayuno",
  "MealSlot.lunch": "Comida",
  "MealSlot.dinner": "Cena",
  "MealSlot.snack": "Merienda",
  "DeadlineArea.car": "Coche",
  "DeadlineArea.home": "Casa y hogar",
  "DeadlineArea.pet": "Mascotas",
  "DeadlineArea.other": "Otros",
  "Checklist|Kliniktasche": "Bolsa para el hospital",
  "Checklist|Erstausstattung": "Canastilla",
  "Checklist|Nach der Geburt": "Después del parto",
  "Holiday|Neujahr": "Año Nuevo",
  "Holiday|Heilige Drei Könige": "Epifanía",
  "Holiday|Karfreitag": "Viernes Santo",
  "Holiday|Ostermontag": "Lunes de Pascua",
  "Holiday|Tag der Arbeit": "Día del Trabajo",
  "Holiday|Christi Himmelfahrt": "Ascensión",
  "Holiday|Pfingstmontag": "Lunes de Pentecostés",
  "Holiday|Fronleichnam": "Corpus Christi",
  "Holiday|Tag der Deutschen Einheit": "Día de la Unidad Alemana",
  "Holiday|Allerheiligen": "Todos los Santos",
  "Holiday|1. Weihnachtstag": "Navidad",
  "Holiday|2. Weihnachtstag": "San Esteban",
  "Holiday|Internationaler Frauentag": "Día Internacional de la Mujer",
  "Holiday|Ostersonntag": "Domingo de Pascua",
  "Holiday|Pfingstsonntag": "Domingo de Pentecostés",
  "Holiday|Reformationstag": "Día de la Reforma",
  "Holiday|Mariä Himmelfahrt": "Asunción",
  "Holiday|Buß- und Bettag": "Día de Penitencia y Oración",
  "Holiday|Weltkindertag": "Día Mundial de la Infancia",
  "ShoppingCategory.produce": "Frutas y verduras",
  "ShoppingCategory.bakery": "Pan y bollería",
  "ShoppingCategory.dairy": "Refrigerados",
  "ShoppingCategory.meat": "Carne, embutidos y pescado",
  "ShoppingCategory.frozen": "Congelados",
  "ShoppingCategory.pantry": "Pasta, arroz y conservas",
  "ShoppingCategory.baking": "Repostería y especias",
  "ShoppingCategory.drinks": "Bebidas",
  "ShoppingCategory.snacks": "Dulces y aperitivos",
  "ShoppingCategory.household": "Droguería y hogar",
  "ShoppingCategory.baby": "Bebé y niño",
  "ShoppingCategory.pet": "Mascotas",
  "ShoppingCategory.other": "Otros",
  "DeadlinePreset|HU/TÜV": "ITV",
  "DeadlinePreset|Monat steht auf der Plakette am hinteren Kennzeichen":
      "El mes está en la pegatina de la matrícula trasera",
  "DeadlinePreset|Inspektion": "Revisión",
  "DeadlinePreset|Winterreifen aufziehen": "Poner neumáticos de invierno",
  "DeadlinePreset|Faustregel: von Oktober bis Ostern":
      "Regla práctica: de octubre a Semana Santa",
  "DeadlinePreset|Sommerreifen aufziehen": "Poner neumáticos de verano",
  "DeadlinePreset|Kfz-Versicherung prüfen": "Revisar el seguro del coche",
  "DeadlinePreset|Verbandkasten tauschen": "Cambiar el botiquín",
  "DeadlinePreset|Heizungswartung": "Mantenimiento de la calefacción",
  "DeadlinePreset|Rauchmelder testen": "Probar los detectores de humo",
  "DeadlinePreset|Schornsteinfeger": "Deshollinador",
  "DeadlinePreset|Wasserfilter wechseln": "Cambiar el filtro de agua",
  "DeadlinePreset|Feuerlöscher prüfen": "Revisar el extintor",
  "DeadlinePreset|Zählerstände ablesen": "Leer los contadores",
  "DeadlinePreset|Impfung": "Vacuna",
  "DeadlinePreset|Entwurmung": "Desparasitación",
  "DeadlinePreset|Floh- und Zeckenschutz":
      "Protección contra pulgas y garrapatas",
  "DeadlinePreset|Tierarzt-Check": "Revisión en el veterinario",
  "DeadlinePreset|Hundesteuer": "Impuesto de perros",
  "ListTemplate|Urlaub": "Vacaciones",
  "ListTemplate|Kita-Tasche": "Mochila de la guardería",
  "ListTemplate|Kliniktasche Geburt": "Bolsa para el parto",
  "ListTemplate|Schwimmbad": "Piscina",
  "ListTemplate|Camping": "Camping",
  "CheckIn|Bin angekommen": "He llegado",
  "CheckIn|Alles ok": "Todo bien",
  "CheckIn|Bin auf dem Heimweg": "De camino a casa",
  "CheckIn|Bitte abholen": "Recógeme, por favor",
  "LocationAlert|{member} ist bei „{place}“ angekommen":
      "{member} ha llegado a «{place}»",
  "LocationAlert|{member} hat „{place}“ verlassen":
      "{member} ha salido de «{place}»",
  "LocationAlert|{member}: {note} (bei „{place}“)":
      "{member}: {note} (en «{place}»)",
  "Recurrence|täglich": "cada día",
  "Recurrence|alle {every} Tage": "cada {every} días",
  "Recurrence|wöchentlich": "cada semana",
  "Recurrence|alle {every} Wochen": "cada {every} semanas",
  "Recurrence|monatlich": "cada mes",
  "Recurrence|alle {every} Monate": "cada {every} meses",
  "Recurrence|jährlich": "cada año",
  "Recurrence|alle {every} Jahre": "cada {every} años",
  "Milestone|Hebt in Bauchlage kurz den Kopf":
      "Levanta un momento la cabeza boca abajo",
  "Milestone|Hält den Kopf sicher": "Sostiene bien la cabeza",
  "Milestone|Dreht sich vom Rücken auf den Bauch":
      "Se da la vuelta de boca arriba a boca abajo",
  "Milestone|Sitzt frei ohne Stütze": "Se sienta sin apoyo",
  "Milestone|Krabbelt auf Händen und Knien": "Gatea sobre manos y rodillas",
  "Milestone|Manche Kinder lassen das Krabbeln ganz aus – das ist normal.":
      "Algunos niños no llegan a gatear: es normal.",
  "Milestone|Steht mit Festhalten": "Se pone de pie agarrado",
  "Milestone|Läuft an Möbeln entlang": "Camina agarrado a los muebles",
  "Milestone|Steht frei": "Se mantiene de pie solo",
  "Milestone|Erste freie Schritte": "Primeros pasos solo",
  "Milestone|Geht Treppen mit Festhalten": "Sube escaleras agarrado",
  "Milestone|Rennt": "Corre",
  "Milestone|Springt mit beiden Beinen": "Salta con los dos pies",
  "Milestone|Fährt Laufrad oder Dreirad":
      "Va en bici sin pedales o en triciclo",
  "Milestone|Steht kurz auf einem Bein":
      "Se sostiene un momento sobre una pierna",
  "Milestone|Fährt Fahrrad ohne Stützräder": "Monta en bici sin ruedines",
  "Milestone|Schwimmt (Seepferdchen)": "Nada (primera insignia de natación)",
  "Milestone|Greift gezielt nach Dingen": "Coge cosas a propósito",
  "Milestone|Gibt Dinge von einer Hand in die andere":
      "Pasa cosas de una mano a otra",
  "Milestone|Pinzettengriff mit Daumen und Zeigefinger":
      "Pinza con el pulgar y el índice",
  "Milestone|Baut einen Turm aus Klötzen": "Construye una torre de bloques",
  "Milestone|Kritzelt mit Stift": "Garabatea con un lápiz",
  "Milestone|Malt einen Kreis": "Dibuja un círculo",
  "Milestone|Schneidet mit der Kinderschere": "Recorta con tijeras infantiles",
  "Milestone|Malt einen Menschen mit Kopf, Armen und Beinen":
      "Dibuja una persona con cabeza, brazos y piernas",
  "Milestone|Gurrt und macht Vokal-Laute": "Hace gorjeos y sonidos de vocales",
  "Milestone|Brabbelt Silbenketten („ba-ba-ba“)":
      "Balbucea cadenas de sílabas («ba-ba-ba»)",
  "Milestone|Erstes Wort mit Bedeutung": "Primera palabra con significado",
  "Milestone|Zweiwortsätze („Mama Auto“)":
      "Frases de dos palabras («mamá coche»)",
  "Milestone|Spricht in kurzen Sätzen": "Habla con frases cortas",
  "Milestone|Stellt „Warum?“-Fragen": "Pregunta «¿por qué?»",
  "Milestone|Erzählt kleine Geschichten": "Cuenta pequeñas historias",
  "Milestone|Liest erste Wörter": "Lee sus primeras palabras",
  "Milestone|Erstes soziales Lächeln": "Primera sonrisa social",
  "Milestone|Lacht laut": "Se ríe a carcajadas",
  "Milestone|Fremdelt": "Extraña a los desconocidos",
  "Milestone|Winkt „Tschüss“": "Dice adiós con la mano",
  "Milestone|Als-ob-Spiel (füttert die Puppe)":
      "Juego simbólico (da de comer a la muñeca)",
  "Milestone|Spielt gemeinsam mit anderen Kindern": "Juega con otros niños",
  "Milestone|Hat eine beste Freundin / einen besten Freund":
      "Tiene un mejor amigo o una mejor amiga",
  "Milestone|Trinkt aus dem Becher": "Bebe de un vaso",
  "Milestone|Isst selbst mit dem Löffel": "Come solo con cuchara",
  "Milestone|Tagsüber trocken": "Sin pañal de día",
  "Milestone|Nachts trocken": "Sin pañal de noche",
  "Milestone|Nachts trocken zu werden dauert oft deutlich länger als tagsüber.":
      "Dejar el pañal de noche suele tardar bastante más que de día.",
  "Milestone|Zieht sich allein an": "Se viste solo",
  "Milestone|Bindet Schuhe selbst": "Se ata los zapatos solo",
  "Milestone|Erster Zahn": "Primer diente",
  "Milestone|Schläft (meist) durch": "Duerme toda la noche (casi siempre)",
  "Milestone|Erster Wackelzahn": "Primer diente que se mueve",
  "Checkup|U1 – Neugeborenen-Erstuntersuchung":
      "U1: primera exploración del recién nacido",
  "Checkup|direkt nach der Geburt": "justo después del parto",
  "Checkup|U2 – Neugeborenen-Basisuntersuchung":
      "U2: exploración básica del recién nacido",
  "Checkup|3.–10. Lebenstag": "días 3–10 de vida",
  "Checkup|U3": "U3",
  "Checkup|4.–5. Lebenswoche": "semanas 4–5 de vida",
  "Checkup|U4": "U4",
  "Checkup|3.–4. Lebensmonat": "meses 3–4 de vida",
  "Checkup|U5": "U5",
  "Checkup|6.–7. Lebensmonat": "meses 6–7 de vida",
  "Checkup|U6": "U6",
  "Checkup|10.–12. Lebensmonat": "meses 10–12 de vida",
  "Checkup|U7": "U7",
  "Checkup|21.–24. Lebensmonat": "meses 21–24 de vida",
  "Checkup|U7a": "U7a",
  "Checkup|34.–36. Lebensmonat": "meses 34–36 de vida",
  "Checkup|U8": "U8",
  "Checkup|46.–48. Lebensmonat": "meses 46–48 de vida",
  "Checkup|U9 – vor der Einschulung": "U9: antes de empezar el colegio",
  "Checkup|60.–64. Lebensmonat": "meses 60–64 de vida",
  "Checkup|U10": "U10",
  "Checkup|7–8 Jahre": "7–8 años",
  "Checkup|U11": "U11",
  "Checkup|9–10 Jahre": "9–10 años",
  "Checkup|J1 – Jugenduntersuchung": "J1: revisión juvenil",
  "Checkup|12–14 Jahre": "12–14 años",
  "Checkup|J2": "J2",
  "Checkup|16–17 Jahre": "16–17 años",
  "Vaccination|RSV (Antikörper-Prophylaxe)": "VRS (profilaxis con anticuerpos)",
  "Vaccination|einmalig": "una vez",
  "Vaccination|Vor bzw. in der ersten RSV-Saison (meist Oktober–März).":
      "Antes o durante la primera temporada de VRS (normalmente octubre–marzo).",
  "Vaccination|Rotaviren": "Rotavirus",
  "Vaccination|1. Dosis": "1.ª dosis",
  "Vaccination|Schluckimpfung ab 6 Wochen.":
      "Vacuna oral a partir de las 6 semanas.",
  "Vaccination|2. Dosis": "2.ª dosis",
  "Vaccination|3. Dosis": "3.ª dosis",
  "Vaccination|Je nach Impfstoff nötig.": "Necesaria según la vacuna.",
  "Vaccination|Sechsfach (Tetanus, Diphtherie, Keuchhusten, Hib, Polio, Hepatitis B)":
      "Hexavalente (tétanos, difteria, tos ferina, Hib, polio, hepatitis B)",
  "Vaccination|Pneumokokken": "Neumococo",
  "Vaccination|Meningokokken B": "Meningococo B",
  "Vaccination|Masern, Mumps, Röteln, Windpocken":
      "Sarampión, paperas, rubéola, varicela",
  "Vaccination|Meningokokken C": "Meningococo C",
  "Vaccination|Für Kita und Schule ist der Masernschutz Pflicht.":
      "En Alemania, la protección contra el sarampión es obligatoria para guardería y colegio.",
  "Vaccination|Tetanus, Diphtherie, Keuchhusten":
      "Tétanos, difteria, tos ferina",
  "Vaccination|Auffrischung": "Refuerzo",
  "Vaccination|Mit 5–6 Jahren.": "A los 5–6 años.",
  "Vaccination|HPV (Humane Papillomviren)": "VPH (virus del papiloma humano)",
  "Vaccination|Mit 9–14 Jahren, für alle Kinder.":
      "A los 9–14 años, para todos los niños.",
  "Vaccination|Mindestens 5 Monate nach der 1. Dosis.":
      "Al menos 5 meses después de la 1.ª dosis.",
  "Vaccination|Tetanus, Diphtherie, Keuchhusten, Polio":
      "Tétanos, difteria, tos ferina, polio",
  "Vaccination|Mit 9–16 Jahren.": "A los 9–16 años.",
  "PregnancyWeek|ein Mohnsamen": "una semilla de amapola",
  "PregnancyWeek|Die Einnistung ist geschafft.":
      "La implantación se ha completado.",
  "PregnancyWeek|ein Sesamkorn": "una semilla de sésamo",
  "PregnancyWeek|Das Herz beginnt sich zu bilden.":
      "El corazón empieza a formarse.",
  "PregnancyWeek|eine Linse": "una lenteja",
  "PregnancyWeek|Im Ultraschall ist oft schon der Herzschlag zu sehen.":
      "En la ecografía a menudo ya se ve el latido.",
  "PregnancyWeek|eine Blaubeere": "un arándano",
  "PregnancyWeek|Ärmchen und Beinchen knospen.":
      "Brotan los bracitos y las piernecitas.",
  "PregnancyWeek|eine Himbeere": "una frambuesa",
  "PregnancyWeek|Finger und Zehen entstehen.":
      "Se forman los dedos de las manos y los pies.",
  "PregnancyWeek|eine Kirsche": "una cereza",
  "PregnancyWeek|Alle Organe sind angelegt.":
      "Todos los órganos están formados.",
  "PregnancyWeek|eine Erdbeere": "una fresa",
  "PregnancyWeek|Aus dem Embryo wird ein Fötus.":
      "El embrión pasa a ser un feto.",
  "PregnancyWeek|eine Feige": "un higo",
  "PregnancyWeek|Das Baby bewegt sich schon – spüren kann man es noch nicht.":
      "El bebé ya se mueve, aunque todavía no se nota.",
  "PregnancyWeek|eine Limette": "una lima",
  "PregnancyWeek|Das erste Drittel ist bald geschafft.":
      "El primer trimestre casi ha terminado.",
  "PregnancyWeek|eine Zitrone": "un limón",
  "PregnancyWeek|Das zweite Trimester beginnt.":
      "Empieza el segundo trimestre.",
  "PregnancyWeek|ein Pfirsich": "un melocotón",
  "PregnancyWeek|Das Baby kann schon Grimassen schneiden.":
      "El bebé ya puede hacer muecas.",
  "PregnancyWeek|ein Apfel": "una manzana",
  "PregnancyWeek|Die Haut ist noch ganz dünn.": "La piel todavía es muy fina.",
  "PregnancyWeek|eine Avocado": "un aguacate",
  "PregnancyWeek|Manche spüren jetzt erste Bewegungen.":
      "Algunas notan ahora los primeros movimientos.",
  "PregnancyWeek|eine Birne": "una pera",
  "PregnancyWeek|Fettpolster beginnen sich zu bilden.":
      "Empiezan a formarse reservas de grasa.",
  "PregnancyWeek|eine Paprika": "un pimiento",
  "PregnancyWeek|Das Baby hört erste Geräusche.":
      "El bebé oye sus primeros sonidos.",
  "PregnancyWeek|eine Mango": "un mango",
  "PregnancyWeek|Bergfest naht!": "¡Pronto llegáis a la mitad!",
  "PregnancyWeek|eine Banane": "un plátano",
  "PregnancyWeek|Halbzeit – ab jetzt wird von Kopf bis Fuß gemessen.":
      "Mitad del camino: a partir de ahora se mide de la cabeza a los pies.",
  "PregnancyWeek|eine Karotte": "una zanahoria",
  "PregnancyWeek|Tritte werden kräftiger.": "Las patadas son más fuertes.",
  "PregnancyWeek|eine Papaya": "una papaya",
  "PregnancyWeek|Das Baby erkennt Stimmen.": "El bebé reconoce voces.",
  "PregnancyWeek|eine Grapefruit": "un pomelo",
  "PregnancyWeek|Die Lunge reift.": "Los pulmones maduran.",
  "PregnancyWeek|ein Maiskolben": "una mazorca de maíz",
  "PregnancyWeek|Ab jetzt hat ein Frühchen gute Chancen.":
      "A partir de ahora, un bebé prematuro tiene buenas posibilidades.",
  "PregnancyWeek|ein Blumenkohl": "una coliflor",
  "PregnancyWeek|Das Baby hat einen Schlaf-Wach-Rhythmus.":
      "El bebé tiene un ritmo de sueño y vigilia.",
  "PregnancyWeek|ein Salatkopf": "una lechuga",
  "PregnancyWeek|Die Augen öffnen sich.": "Se abren los ojos.",
  "PregnancyWeek|ein Brokkoli": "un brócoli",
  "PregnancyWeek|Das zweite Trimester endet.": "Termina el segundo trimestre.",
  "PregnancyWeek|eine Aubergine": "una berenjena",
  "PregnancyWeek|Das letzte Drittel beginnt.": "Empieza el último trimestre.",
  "PregnancyWeek|ein Butternusskürbis": "una calabaza moscada",
  "PregnancyWeek|Muskeln und Lunge reifen weiter.":
      "Los músculos y los pulmones siguen madurando.",
  "PregnancyWeek|ein Kohlkopf": "una col",
  "PregnancyWeek|Das Gehirn wächst schnell.": "El cerebro crece rápidamente.",
  "PregnancyWeek|eine Kokosnuss": "un coco",
  "PregnancyWeek|Es wird eng im Bauch.":
      "Empieza a faltar espacio en la barriga.",
  "PregnancyWeek|ein Hokkaido-Kürbis": "una calabaza hokkaido",
  "PregnancyWeek|Die meisten Babys drehen sich jetzt mit dem Kopf nach unten.":
      "La mayoría de los bebés se colocan ahora cabeza abajo.",
  "PregnancyWeek|eine Ananas": "una piña",
  "PregnancyWeek|Die Knochen härten aus – bis auf den Schädel.":
      "Los huesos se endurecen, salvo el cráneo.",
  "PregnancyWeek|eine Honigmelone": "un melón",
  "PregnancyWeek|Zeit, die Kliniktasche zu packen.":
      "Es hora de preparar la bolsa para el hospital.",
  "PregnancyWeek|eine Galiamelone": "un melón galia",
  "PregnancyWeek|Das Baby legt vor allem an Gewicht zu.":
      "El bebé sobre todo gana peso.",
  "PregnancyWeek|ein Römersalat": "una lechuga romana",
  "PregnancyWeek|Ab jetzt heißt es: bereit sein.":
      "A partir de ahora: estad preparados.",
  "PregnancyWeek|ein Mangold": "un manojo de acelgas",
  "PregnancyWeek|Ab 37+0 gilt das Baby als reif geboren.":
      "A partir de 37+0 el bebé se considera a término.",
  "PregnancyWeek|eine Lauchstange": "un puerro",
  "PregnancyWeek|Jeden Tag kann es losgehen.": "Puede empezar cualquier día.",
  "PregnancyWeek|eine kleine Wassermelone": "una sandía pequeña",
  "PregnancyWeek|Die Käseschmiere wird weniger.": "El vérnix disminuye.",
  "PregnancyWeek|ein Kürbis": "una calabaza",
  "PregnancyWeek|Der errechnete Termin ist da – nur wenige Babys kommen genau heute.":
      "Ha llegado la fecha prevista: pocos bebés nacen justo hoy.",
  "PregnancyTask|Hebamme suchen": "Buscar matrona",
  "PregnancyTask|Hebammen sind oft früh ausgebucht – für Vorsorge und Wochenbett am besten gleich nach dem positiven Test anfragen.":
      "Las matronas suelen tener la agenda llena pronto: lo mejor es preguntar justo después del test positivo, para el control prenatal y el posparto.",
  "PregnancyTask|1. Ultraschall-Screening": "1.ª ecografía de control",
  "PregnancyTask|Mutterpass: 9+0 bis 12+6.":
      "Cartilla de embarazo: 9+0 a 12+6.",
  "PregnancyTask|Geburtsvorbereitungskurs anmelden":
      "Apuntarse a un curso de preparación al parto",
  "PregnancyTask|Der Kurs selbst liegt meist zwischen SSW 25 und 35.":
      "El curso suele ser entre la semana 25 y la 35.",
  "PregnancyTask|2. Ultraschall-Screening": "2.ª ecografía de control",
  "PregnancyTask|Mutterpass: 19+0 bis 22+6.":
      "Cartilla de embarazo: 19+0 a 22+6.",
  "PregnancyTask|Zuckertest (Glukose)": "Prueba de glucosa",
  "PregnancyTask|Test auf Schwangerschaftsdiabetes: 24+0 bis 27+6.":
      "Prueba de diabetes gestacional: 24+0 a 27+6.",
  "PregnancyTask|Keuchhusten-Impfung": "Vacuna de la tos ferina",
  "PregnancyTask|STIKO: zu Beginn des letzten Drittels – schützt das Baby in den ersten Monaten.":
      "STIKO: al principio del último trimestre; protege al bebé en los primeros meses.",
  "PregnancyTask|3. Ultraschall-Screening": "3.ª ecografía de control",
  "PregnancyTask|Mutterpass: 29+0 bis 32+6.":
      "Cartilla de embarazo: 29+0 a 32+6.",
  "PregnancyTask|In der Geburtsklinik anmelden":
      "Inscribirse en el hospital para el parto",
  "PregnancyTask|Oft mit Vorgespräch und Kreißsaalführung.":
      "A menudo con una entrevista previa y una visita a la sala de partos.",
  "PregnancyTask|Kinderarzt suchen": "Buscar pediatra",
  "PregnancyTask|Für die U2 und die weiteren Vorsorgen.":
      "Para la U2 y las revisiones siguientes.",
  "PregnancyTask|Kliniktasche packen": "Preparar la bolsa para el hospital",
  "PregnancyTask|Siehe Checkliste.": "Ver la lista.",
  "PregnancyTask|Mutterschaftsgeld beantragen":
      "Solicitar la prestación por maternidad",
  "PregnancyTask|Bei der Krankenkasse, mit Bescheinigung über den Termin (frühestens 7 Wochen vor ET). Mutterschutz beginnt 6 Wochen vor ET.":
      "En el seguro médico, con un certificado de la fecha prevista (como muy pronto 7 semanas antes). En Alemania, la protección por maternidad empieza 6 semanas antes de la fecha prevista.",
  "ChecklistItem|Mutterpass, Versichertenkarte, Personalausweis":
      "Cartilla de embarazo, tarjeta sanitaria, documento de identidad",
  "ChecklistItem|Familienstammbuch bzw. Geburts-/Heiratsurkunde":
      "Libro de familia o certificado de nacimiento/matrimonio",
  "ChecklistItem|Bequeme Kleidung, Bademantel, Hausschuhe":
      "Ropa cómoda, albornoz, zapatillas",
  "ChecklistItem|Still-BH, Stilleinlagen, Wochenbett-Unterhosen":
      "Sujetador de lactancia, discos de lactancia, braguitas posparto",
  "ChecklistItem|Kulturbeutel, Haargummi, Lippenpflege":
      "Neceser, goma del pelo, bálsamo labial",
  "ChecklistItem|Snacks und Getränke für die Geburt":
      "Tentempiés y bebidas para el parto",
  "ChecklistItem|Handy-Ladekabel": "Cargador del móvil",
  "ChecklistItem|Babykleidung für die Heimfahrt (Body, Strampler, Mütze, Jäckchen)":
      "Ropa del bebé para volver a casa (body, pelele, gorro, chaquetita)",
  "ChecklistItem|Babyschale fürs Auto (einbauen üben!)":
      "Silla de coche para el bebé (¡practica cómo instalarla!)",
  "ChecklistItem|Beistellbett oder Babybett mit fester Matratze":
      "Cuna de colecho o cuna con colchón firme",
  "ChecklistItem|Schlafsäcke (keine Decke, kein Kissen)":
      "Sacos de dormir (sin manta ni almohada)",
  "ChecklistItem|Kinderwagen oder Trage": "Carrito o mochila portabebés",
  "ChecklistItem|Bodys und Strampler (Gr. 50/56 und 62)":
      "Bodies y peleles (tallas 50/56 y 62)",
  "ChecklistItem|Windeln, Feuchttücher oder Waschlappen":
      "Pañales, toallitas o manoplas de baño",
  "ChecklistItem|Wickelunterlage, Wundschutzcreme":
      "Cambiador, crema para el culito",
  "ChecklistItem|Badethermometer, Kapuzenhandtuch":
      "Termómetro de baño, toalla con capucha",
  "ChecklistItem|Fieberthermometer": "Termómetro",
  "ChecklistItem|Geburt beim Standesamt anzeigen (innerhalb einer Woche; oft über die Klinik)":
      "Inscribir el nacimiento en el registro civil (en una semana; a menudo a través del hospital)",
  "ChecklistItem|Baby bei der Krankenkasse anmelden":
      "Dar de alta al bebé en el seguro médico",
  "ChecklistItem|Kindergeld bei der Familienkasse beantragen":
      "Solicitar la prestación por hijo",
  "ChecklistItem|Elterngeld beantragen (rückwirkend nur 3 Monate)":
      "Solicitar la prestación parental (solo 3 meses con carácter retroactivo)",
  "ChecklistItem|Arbeitgeber informieren, Elternzeit anmelden (7 Wochen vorher)":
      "Informar a la empresa y solicitar el permiso parental (7 semanas antes)",
  "ChecklistItem|Termin für die U2 (3.–10. Lebenstag)":
      "Cita para la U2 (días 3–10 de vida)",
  "ChecklistItem|Wochenbett-Hebamme bestätigen":
      "Confirmar la matrona del posparto",
  "TemplateItem|Ausweise & Reisepässe": "Documentos de identidad y pasaportes",
  "TemplateItem|Krankenversichertenkarten": "Tarjetas sanitarias",
  "TemplateItem|Buchungsbestätigungen": "Confirmaciones de reserva",
  "TemplateItem|Unterwäsche & Socken": "Ropa interior y calcetines",
  "TemplateItem|Schlafanzüge": "Pijamas",
  "TemplateItem|Regenjacken": "Chubasqueros",
  "TemplateItem|Badesachen": "Bañadores",
  "TemplateItem|Zahnbürsten & Zahnpasta": "Cepillos y pasta de dientes",
  "TemplateItem|Sonnencreme": "Crema solar",
  "TemplateItem|Reiseapotheke": "Botiquín de viaje",
  "TemplateItem|Ladegeräte": "Cargadores",
  "TemplateItem|Kuscheltier": "Peluche",
  "TemplateItem|Spiele & Bücher für die Fahrt": "Juegos y libros para el viaje",
  "TemplateItem|Snacks & Getränke": "Tentempiés y bebidas",
  "TemplateItem|Wechselkleidung": "Ropa de recambio",
  "TemplateItem|Windeln & Feuchttücher": "Pañales y toallitas",
  "TemplateItem|Matschhose & Gummistiefel":
      "Pantalón impermeable y botas de agua",
  "TemplateItem|Hausschuhe": "Zapatillas de casa",
  "TemplateItem|Trinkflasche": "Botella de agua",
  "TemplateItem|Brotdose": "Fiambrera",
  "TemplateItem|Sonnenhut / Mütze": "Gorro de sol / gorra",
  "TemplateItem|Mutterpass": "Cartilla de embarazo",
  "TemplateItem|Versichertenkarte & Ausweis":
      "Tarjeta sanitaria y documento de identidad",
  "TemplateItem|Familienstammbuch / Geburtsurkunden":
      "Libro de familia / certificados de nacimiento",
  "TemplateItem|Bequeme Kleidung & Bademantel": "Ropa cómoda y albornoz",
  "TemplateItem|Still-BHs & Stilleinlagen": "Sujetadores y discos de lactancia",
  "TemplateItem|Hausschuhe & warme Socken":
      "Zapatillas y calcetines calentitos",
  "TemplateItem|Kulturbeutel": "Neceser",
  "TemplateItem|Ladekabel": "Cable de carga",
  "TemplateItem|Erstausstattung Baby": "Canastilla del bebé",
  "TemplateItem|Mützchen & Söckchen": "Gorrito y calcetines",
  "TemplateItem|Babyschale fürs Auto": "Silla de coche para el bebé",
  "TemplateItem|Handtücher": "Toallas",
  "TemplateItem|Schwimmflügel": "Manguitos",
  "TemplateItem|Duschgel & Shampoo": "Gel y champú",
  "TemplateItem|Haarbürste": "Cepillo del pelo",
  "TemplateItem|Münzen für den Spind": "Monedas para la taquilla",
  "TemplateItem|Snacks": "Tentempiés",
  "TemplateItem|Zelt & Heringe": "Tienda y piquetas",
  "TemplateItem|Schlafsäcke & Isomatten": "Sacos de dormir y esterillas",
  "TemplateItem|Stirnlampen": "Linternas frontales",
  "TemplateItem|Campingkocher & Gas": "Hornillo de camping y gas",
  "TemplateItem|Geschirr & Besteck": "Platos y cubiertos",
  "TemplateItem|Mückenschutz": "Repelente de mosquitos",
  "TemplateItem|Erste-Hilfe-Set": "Botiquín",
};
