/// Aisles of a typical German supermarket, in walking order, and a small
/// dictionary (German, English and Spanish words) that puts a shopping item
/// into one. The family's own corrections win over the dictionary (see
/// [guessShoppingCategory]).
library;

import '../texts.dart';

class ShoppingCategory {
  const ShoppingCategory(this.key, this._label, this.words);

  /// Stored in `ShoppingItem.category`.
  final String key;
  final String _label;
  String get label => sharedText('ShoppingCategory.$key', _label);

  /// Lower-case word parts; an item matches if its name contains one
  /// ("Vollmilch" contains "milch"). The longest match wins.
  final List<String> words;
}

const shoppingCategories = [
  ShoppingCategory('produce', 'Obst & Gemüse', [
    'apfel',
    'äpfel',
    'banane',
    'birne',
    'orange',
    'mandarine',
    'zitrone',
    'limette',
    'traube',
    'erdbeer',
    'himbeer',
    'heidelbeer',
    'blaubeer',
    'kiwi',
    'mango',
    'ananas',
    'melone',
    'pfirsich',
    'nektarine',
    'pflaume',
    'kirsche',
    'avocado',
    'tomate',
    'gurke',
    'paprika',
    'salat',
    'rucola',
    'spinat',
    'karotte',
    'möhre',
    'kartoffel',
    'zwiebel',
    'knoblauch',
    'lauch',
    'porree',
    'zucchini',
    'aubergine',
    'brokkoli',
    'blumenkohl',
    'kohl',
    'pilz',
    'champignon',
    'sellerie',
    'radieschen',
    'ingwer',
    'kräuter',
    'petersilie',
    'basilikum',
    'schnittlauch',
    'dill',
    'mais',
    'kürbis',
    'spargel',
    'bohnen',
    'erbsen',
    'süßkartoffel',
    'obst',
    'gemüse',
    'beeren',
    'fenchel',
    'rote bete',
    'kohlrabi',
    'corn on the cob',
    'judías verdes',
    'sweet potato',
    'bell pepper',
    'green beans',
    'apple',
    'banana',
    'pear',
    'tangerine',
    'lemon',
    'lime',
    'grape',
    'strawberr',
    'raspberr',
    'blueberr',
    'peach',
    'plum',
    'cherr',
    'tomato',
    'cucumber',
    'lettuce',
    'spinach',
    'carrot',
    'potato',
    'onion',
    'garlic',
    'leek',
    'eggplant',
    'broccoli',
    'cauliflower',
    'cabbage',
    'mushroom',
    'celery',
    'radish',
    'ginger',
    'herbs',
    'parsley',
    'basil',
    'chives',
    'pumpkin',
    'asparagus',
    'peas',
    'fruit',
    'vegetable',
    'berries',
    'fennel',
    'beetroot',
    'manzana',
    'plátano',
    'platano',
    'pera',
    'naranja',
    'mandarina',
    'limón',
    'limon',
    'lima',
    'uva',
    'fresa',
    'frambuesa',
    'arándano',
    'melocotón',
    'ciruela',
    'cereza',
    'aguacate',
    'pepino',
    'pimiento',
    'lechuga',
    'espinaca',
    'zanahoria',
    'patata',
    'cebolla',
    'ajo',
    'puerro',
    'calabacín',
    'berenjena',
    'brócoli',
    'coliflor',
    'col',
    'champiñón',
    'seta',
    'apio',
    'rábano',
    'jengibre',
    'perejil',
    'albahaca',
    'calabaza',
    'espárrago',
    'guisantes',
    'boniato',
    'fruta',
    'verdura',
    'hinojo',
    'remolacha',
  ]),
  ShoppingCategory('bakery', 'Brot & Backwaren', [
    'brot',
    'brötchen',
    'semmel',
    'toast',
    'baguette',
    'croissant',
    'brezel',
    'laugen',
    'knäcke',
    'zwieback',
    'kuchen',
    'wraps',
    'tortilla',
    'fladenbrot',
    'ciabatta',
    'bread',
    'bun',
    'roll',
    'bagel',
    'muffin',
    'cake',
    'pan',
    'barra',
    'panecillo',
    'tostada',
    'bollo',
    'magdalena',
    'bizcocho',
    'tarta',
  ]),
  ShoppingCategory('dairy', 'Kühlregal', [
    'milch',
    'joghurt',
    'jogurt',
    'quark',
    'sahne',
    'schmand',
    'butter',
    'margarine',
    'käse',
    'mozzarella',
    'feta',
    'parmesan',
    'gouda',
    'frischkäse',
    'skyr',
    'kefir',
    'buttermilch',
    'pudding',
    'eier',
    'ei ',
    'tofu',
    'hummus',
    'aufstrich',
    'teig',
    'gnocchi',
    'saft frisch',
    'crème fraîche',
    'creme fraiche',
    'schmelzkäse',
    'hafermilch',
    'bebida de avena',
    'oat milk',
    'milk',
    'yogurt',
    'yoghurt',
    'cream',
    'cheese',
    'eggs',
    'egg',
    'dough',
    'leche',
    'yogur',
    'nata',
    'mantequilla',
    'queso',
    'huevo',
    'masa',
  ]),
  ShoppingCategory('meat', 'Fleisch, Wurst & Fisch', [
    'fleisch',
    'hack',
    'hähnchen',
    'huhn',
    'hühnchen',
    'pute',
    'rind',
    'schwein',
    'schnitzel',
    'steak',
    'wurst',
    'würstchen',
    'salami',
    'schinken',
    'speck',
    'bacon',
    'aufschnitt',
    'leberwurst',
    'fisch',
    'lachs',
    'thunfisch',
    'garnelen',
    'forelle',
    'hering',
    'frikadelle',
    'bratwurst',
    'gulasch',
    'lamm',
    'ground beef',
    'meat',
    'mince',
    'chicken',
    'turkey',
    'beef',
    'pork',
    'sausage',
    'ham',
    'fish',
    'salmon',
    'tuna',
    'shrimp',
    'prawn',
    'trout',
    'lamb',
    'carne',
    'picada',
    'pollo',
    'pavo',
    'ternera',
    'cerdo',
    'salchicha',
    'jamón',
    'jamon',
    'panceta',
    'beicon',
    'pescado',
    'salmón',
    'atún',
    'atun',
    'gamba',
    'merluza',
    'cordero',
  ]),
  ShoppingCategory('frozen', 'Tiefkühl', [
    'tiefkühl',
    'tk ',
    'tk-',
    'pizza',
    'eis',
    'eiscreme',
    'pommes',
    'fischstäbchen',
    'spinat tk',
    'gefroren',
    'eiswürfel',
    'palitos de pescado',
    'patatas fritas',
    'fish sticks',
    'ice cream',
    'ice cubes',
    'frozen',
    'fries',
    'congelad',
    'helado',
    'cubitos',
  ]),
  ShoppingCategory('pantry', 'Nudeln, Reis & Konserven', [
    'nudel',
    'spaghetti',
    'penne',
    'fusilli',
    'lasagne',
    'pasta',
    'reis',
    'couscous',
    'bulgur',
    'quinoa',
    'linsen',
    'kichererbsen',
    'dose',
    'konserve',
    'passierte',
    'tomatenmark',
    'suppe',
    'brühe',
    'fond',
    'müsli',
    'haferflocken',
    'cornflakes',
    'flakes',
    'marmelade',
    'konfitüre',
    'honig',
    'nutella',
    'erdnussbutter',
    'öl',
    'essig',
    'senf',
    'ketchup',
    'mayo',
    'mayonnaise',
    'soße',
    'sauce',
    'pesto',
    'oliven',
    'gurken glas',
    'sauerkraut',
    'copos de avena',
    'peanut butter',
    'tomato paste',
    'tomate frito',
    'noodle',
    'rice',
    'lentil',
    'chickpea',
    'canned',
    'soup',
    'broth',
    'cereal',
    'oats',
    'jam',
    'honey',
    'oil',
    'vinegar',
    'mustard',
    'olives',
    'pickles',
    'fideo',
    'macarrones',
    'espagueti',
    'arroz',
    'lenteja',
    'garbanzo',
    'lata',
    'conserva',
    'sopa',
    'caldo',
    'cereales',
    'mermelada',
    'miel',
    'aceite',
    'vinagre',
    'mostaza',
    'mayonesa',
    'salsa',
    'aceitunas',
  ]),
  ShoppingCategory('baking', 'Backen & Gewürze', [
    'mehl',
    'zucker',
    'backpulver',
    'hefe',
    'vanille',
    'zimt',
    'salz',
    'pfeffer',
    'gewürz',
    'paprikapulver',
    'oregano',
    'curry',
    'kakao',
    'schokostreusel',
    'puderzucker',
    'speisestärke',
    'gelatine',
    'nüsse',
    'mandeln',
    'rosinen',
    'backpapier',
    'papel de horno',
    'baking powder',
    'baking paper',
    'flour',
    'sugar',
    'yeast',
    'vanilla',
    'cinnamon',
    'salt',
    'pepper',
    'spice',
    'cocoa',
    'nuts',
    'almonds',
    'raisins',
    'harina',
    'azúcar',
    'azucar',
    'levadura',
    'vainilla',
    'canela',
    'pimienta',
    'especia',
    'cacao',
    'almendras',
    'pasas',
  ]),
  ShoppingCategory('drinks', 'Getränke', [
    'wasser',
    'sprudel',
    'saft',
    'schorle',
    'limo',
    'cola',
    'fanta',
    'bier',
    'wein',
    'sekt',
    'kaffee',
    'tee',
    'espresso',
    'kapseln',
    'pads',
    'sirup',
    'eistee',
    'mate',
    'energy',
    'iced tea',
    'water',
    'sparkling',
    'juice',
    'soda',
    'lemonade',
    'beer',
    'wine',
    'coffee',
    'tea',
    'capsules',
    'syrup',
    'agua',
    'zumo',
    'refresco',
    'gaseosa',
    'cerveza',
    'vino',
    'café',
    'cafe',
    'té',
    'infusión',
    'cápsulas',
  ]),
  ShoppingCategory('snacks', 'Süßes & Snacks', [
    'schokolade',
    'schoko',
    'keks',
    'gummibär',
    'chips',
    'flips',
    'salzstangen',
    'bonbon',
    'riegel',
    'nüsse gesalzen',
    'popcorn',
    'süßigkeit',
    'kaugummi',
    'lakritz',
    'waffeln',
    'cracker',
    'patatas chips',
    'chewing gum',
    'chocolate',
    'cookie',
    'biscuit',
    'gummy',
    'crisps',
    'pretzel',
    'candy',
    'bar',
    'licorice',
    'crackers',
    'galleta',
    'gominola',
    'caramelo',
    'palomitas',
    'chicle',
    'regaliz',
  ]),
  ShoppingCategory('household', 'Drogerie & Haushalt', [
    'klopapier',
    'toilettenpapier',
    'küchenrolle',
    'taschentücher',
    'spülmittel',
    'spültabs',
    'tabs',
    'waschmittel',
    'weichspüler',
    'reiniger',
    'putz',
    'schwamm',
    'müllbeutel',
    'müllsäcke',
    'folie',
    'alufolie',
    'frischhaltefolie',
    'gefrierbeutel',
    'zahnpasta',
    'zahnbürste',
    'zahnseide',
    'shampoo',
    'duschgel',
    'seife',
    'deo',
    'creme',
    'sonnencreme',
    'rasier',
    'binden',
    'tampons',
    'watte',
    'pflaster',
    'batterien',
    'glühbirne',
    'kerzen',
    'servietten',
    'cepillo de dientes',
    'papel de aluminio',
    'film transparente',
    'bolsas de basura',
    'pasta de dientes',
    'dishwasher tabs',
    'fabric softener',
    'papel higiénico',
    'papel de cocina',
    'toilet paper',
    'kitchen roll',
    'freezer bags',
    'gel de ducha',
    'hilo dental',
    'crema solar',
    'trash bags',
    'cling film',
    'shower gel',
    'light bulb',
    'dish soap',
    'bin bags',
    'tissues',
    'detergent',
    'cleaner',
    'sponge',
    'foil',
    'toothpaste',
    'toothbrush',
    'floss',
    'soap',
    'deodorant',
    'lotion',
    'sunscreen',
    'razor',
    'pads',
    'cotton',
    'plasters',
    'band-aid',
    'batteries',
    'candles',
    'napkins',
    'pañuelos',
    'lavavajillas',
    'detergente',
    'suavizante',
    'limpiador',
    'estropajo',
    'champú',
    'jabón',
    'desodorante',
    'cuchilla',
    'compresas',
    'tampones',
    'algodón',
    'tiritas',
    'pilas',
    'bombilla',
    'velas',
    'servilletas',
  ]),
  ShoppingCategory('baby', 'Baby & Kind', [
    'windel',
    'feuchttücher',
    'babybrei',
    'brei',
    'gläschen',
    'pre-milch',
    'folgemilch',
    'schnuller',
    'babyshampoo',
    'wundschutz',
    'leche de continuación',
    'baby food',
    'diaper',
    'wipes',
    'formula',
    'pacifier',
    'pañal',
    'toallitas',
    'potito',
    'chupete',
  ]),
  ShoppingCategory('pet', 'Tierbedarf', [
    'katzenfutter',
    'hundefutter',
    'futter',
    'katzenstreu',
    'streu',
    'leckerli',
    'comida para perros',
    'comida para gatos',
    'arena para gatos',
    'cat litter',
    'cat food',
    'dog food',
    'pet food',
    'treats',
    'pienso',
    'chuches',
  ]),
  ShoppingCategory('other', 'Sonstiges', []),
];

/// The category with [key], or null.
ShoppingCategory? shoppingCategory(String key) {
  for (final c in shoppingCategories) {
    if (c.key == key) return c;
  }
  return null;
}

/// Lower case, single spaces, no quantities in front: the key the family's
/// corrections are remembered under.
String shoppingKey(String name) => name
    .trim()
    .toLowerCase()
    .replaceAll(RegExp(r'^\d+\s*[x×]?\s*'), '')
    .replaceAll(RegExp(r'\s+'), ' ')
    .trim();

/// The aisle for [name]: what the family chose for it before ([learned]:
/// [shoppingKey] → category key), else the dictionary, else "other".
String guessShoppingCategory(
  String name, {
  Map<String, String> learned = const {},
}) {
  final key = shoppingKey(name);
  if (key.isEmpty) return 'other';
  final known = learned[key];
  if (known != null && shoppingCategory(known) != null) return known;
  // Padded, so "ei " only matches the word "Ei", not "Eis".
  final padded = '$key ';
  String? best;
  var bestLength = 0;
  for (final c in shoppingCategories) {
    for (final w in c.words) {
      if (w.length > bestLength && padded.contains(w)) {
        best = c.key;
        bestLength = w.length;
      }
    }
  }
  return best ?? 'other';
}
