/// Aisles of a typical German supermarket, in walking order, and a small
/// dictionary that puts a shopping item into one. The family's own
/// corrections win over the dictionary (see [guessShoppingCategory]).
library;

class ShoppingCategory {
  const ShoppingCategory(this.key, this.label, this.words);

  /// Stored in `ShoppingItem.category`.
  final String key;
  final String label;

  /// Lower-case word parts; an item matches if its name contains one
  /// ("Vollmilch" contains "milch"). The longest match wins.
  final List<String> words;
}

const shoppingCategories = [
  ShoppingCategory('produce', 'Obst & Gemüse', [
    'apfel',
    'äpfel',
    'banane',
    'birne',
    'orange',
    'mandarine',
    'zitrone',
    'limette',
    'traube',
    'erdbeer',
    'himbeer',
    'heidelbeer',
    'blaubeer',
    'kiwi',
    'mango',
    'ananas',
    'melone',
    'pfirsich',
    'nektarine',
    'pflaume',
    'kirsche',
    'avocado',
    'tomate',
    'gurke',
    'paprika',
    'salat',
    'rucola',
    'spinat',
    'karotte',
    'möhre',
    'kartoffel',
    'zwiebel',
    'knoblauch',
    'lauch',
    'porree',
    'zucchini',
    'aubergine',
    'brokkoli',
    'blumenkohl',
    'kohl',
    'pilz',
    'champignon',
    'sellerie',
    'radieschen',
    'ingwer',
    'kräuter',
    'petersilie',
    'basilikum',
    'schnittlauch',
    'dill',
    'mais',
    'kürbis',
    'spargel',
    'bohnen',
    'erbsen',
    'süßkartoffel',
    'obst',
    'gemüse',
    'beeren',
    'fenchel',
    'rote bete',
    'kohlrabi',
  ]),
  ShoppingCategory('bakery', 'Brot & Backwaren', [
    'brot',
    'brötchen',
    'semmel',
    'toast',
    'baguette',
    'croissant',
    'brezel',
    'laugen',
    'knäcke',
    'zwieback',
    'kuchen',
    'wraps',
    'tortilla',
    'fladenbrot',
    'ciabatta',
  ]),
  ShoppingCategory('dairy', 'Kühlregal', [
    'milch',
    'joghurt',
    'jogurt',
    'quark',
    'sahne',
    'schmand',
    'butter',
    'margarine',
    'käse',
    'mozzarella',
    'feta',
    'parmesan',
    'gouda',
    'frischkäse',
    'skyr',
    'kefir',
    'buttermilch',
    'pudding',
    'eier',
    'ei ',
    'tofu',
    'hummus',
    'aufstrich',
    'teig',
    'gnocchi',
    'saft frisch',
    'crème fraîche',
    'creme fraiche',
    'schmelzkäse',
    'hafermilch',
  ]),
  ShoppingCategory('meat', 'Fleisch, Wurst & Fisch', [
    'fleisch',
    'hack',
    'hähnchen',
    'huhn',
    'hühnchen',
    'pute',
    'rind',
    'schwein',
    'schnitzel',
    'steak',
    'wurst',
    'würstchen',
    'salami',
    'schinken',
    'speck',
    'bacon',
    'aufschnitt',
    'leberwurst',
    'fisch',
    'lachs',
    'thunfisch',
    'garnelen',
    'forelle',
    'hering',
    'frikadelle',
    'bratwurst',
    'gulasch',
    'lamm',
  ]),
  ShoppingCategory('frozen', 'Tiefkühl', [
    'tiefkühl',
    'tk ',
    'tk-',
    'pizza',
    'eis',
    'eiscreme',
    'pommes',
    'fischstäbchen',
    'spinat tk',
    'gefroren',
    'eiswürfel',
  ]),
  ShoppingCategory('pantry', 'Nudeln, Reis & Konserven', [
    'nudel',
    'spaghetti',
    'penne',
    'fusilli',
    'lasagne',
    'pasta',
    'reis',
    'couscous',
    'bulgur',
    'quinoa',
    'linsen',
    'kichererbsen',
    'dose',
    'konserve',
    'passierte',
    'tomatenmark',
    'suppe',
    'brühe',
    'fond',
    'müsli',
    'haferflocken',
    'cornflakes',
    'flakes',
    'marmelade',
    'konfitüre',
    'honig',
    'nutella',
    'erdnussbutter',
    'öl',
    'essig',
    'senf',
    'ketchup',
    'mayo',
    'mayonnaise',
    'soße',
    'sauce',
    'pesto',
    'oliven',
    'gurken glas',
    'sauerkraut',
  ]),
  ShoppingCategory('baking', 'Backen & Gewürze', [
    'mehl',
    'zucker',
    'backpulver',
    'hefe',
    'vanille',
    'zimt',
    'salz',
    'pfeffer',
    'gewürz',
    'paprikapulver',
    'oregano',
    'curry',
    'kakao',
    'schokostreusel',
    'puderzucker',
    'speisestärke',
    'gelatine',
    'nüsse',
    'mandeln',
    'rosinen',
    'backpapier',
  ]),
  ShoppingCategory('drinks', 'Getränke', [
    'wasser',
    'sprudel',
    'saft',
    'schorle',
    'limo',
    'cola',
    'fanta',
    'bier',
    'wein',
    'sekt',
    'kaffee',
    'tee',
    'espresso',
    'kapseln',
    'pads',
    'sirup',
    'eistee',
    'mate',
    'energy',
  ]),
  ShoppingCategory('snacks', 'Süßes & Snacks', [
    'schokolade',
    'schoko',
    'keks',
    'gummibär',
    'chips',
    'flips',
    'salzstangen',
    'bonbon',
    'riegel',
    'nüsse gesalzen',
    'popcorn',
    'süßigkeit',
    'kaugummi',
    'lakritz',
    'waffeln',
    'cracker',
  ]),
  ShoppingCategory('household', 'Drogerie & Haushalt', [
    'klopapier',
    'toilettenpapier',
    'küchenrolle',
    'taschentücher',
    'spülmittel',
    'spültabs',
    'tabs',
    'waschmittel',
    'weichspüler',
    'reiniger',
    'putz',
    'schwamm',
    'müllbeutel',
    'müllsäcke',
    'folie',
    'alufolie',
    'frischhaltefolie',
    'gefrierbeutel',
    'zahnpasta',
    'zahnbürste',
    'zahnseide',
    'shampoo',
    'duschgel',
    'seife',
    'deo',
    'creme',
    'sonnencreme',
    'rasier',
    'binden',
    'tampons',
    'watte',
    'pflaster',
    'batterien',
    'glühbirne',
    'kerzen',
    'servietten',
  ]),
  ShoppingCategory('baby', 'Baby & Kind', [
    'windel',
    'feuchttücher',
    'babybrei',
    'brei',
    'gläschen',
    'pre-milch',
    'folgemilch',
    'schnuller',
    'babyshampoo',
    'wundschutz',
  ]),
  ShoppingCategory('pet', 'Tierbedarf', [
    'katzenfutter',
    'hundefutter',
    'futter',
    'katzenstreu',
    'streu',
    'leckerli',
  ]),
  ShoppingCategory('other', 'Sonstiges', []),
];

/// The category with [key], or null.
ShoppingCategory? shoppingCategory(String key) {
  for (final c in shoppingCategories) {
    if (c.key == key) return c;
  }
  return null;
}

/// Lower case, single spaces, no quantities in front: the key the family's
/// corrections are remembered under.
String shoppingKey(String name) => name
    .trim()
    .toLowerCase()
    .replaceAll(RegExp(r'^\d+\s*[x×]?\s*'), '')
    .replaceAll(RegExp(r'\s+'), ' ')
    .trim();

/// The aisle for [name]: what the family chose for it before ([learned]:
/// [shoppingKey] → category key), else the dictionary, else "other".
String guessShoppingCategory(
  String name, {
  Map<String, String> learned = const {},
}) {
  final key = shoppingKey(name);
  if (key.isEmpty) return 'other';
  final known = learned[key];
  if (known != null && shoppingCategory(known) != null) return known;
  // Padded, so "ei " only matches the word "Ei", not "Eis".
  final padded = '$key ';
  String? best;
  var bestLength = 0;
  for (final c in shoppingCategories) {
    for (final w in c.words) {
      if (w.length > bestLength && padded.contains(w)) {
        best = c.key;
        bestLength = w.length;
      }
    }
  }
  return best ?? 'other';
}
